hide_enchants: true #hides the enchantment tooltip
fill_lapis: true #fills second slot with lapis (can't be taken by players)
randomize_enchants: true #randomizes the enchantments every time the item is clicked
xpmod: 0.2 #multiply all xp drops by this
loot_mult: 1.5 #multiply xp by this for each level of looting
emerald_crafting: true #enables crafting xp bottles into emeralds
block_natural_exp: true #disables xp from dropping. xp from bottles will be given to players directly
infinite_enchant: true #allows infinite enchanting instead of unrepairable items
exp_per_bottle: 10 #the amount of xp each bottle should give and hold
#give a special xp modifier to certain mobs
entities:
  ENDER_DRAGON: 0.1